name: Run Tests and Format Code

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format_and_save:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
        # Check out the code for formatting

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Format code
        run: npm run format

      - name: Commit formatted code
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add -A
          git commit -m "Format code" || exit 0  # This command will exit with 0 even if there's nothing to commit
        # Commit changes if there are any

      - name: Push changes
        run: git push
        # Push changes back to the repository

  tests:
    runs-on: ubuntu-latest
    needs: format_and_save  # Ensures tests occur after formatting is completed and changes are saved
    steps:
      - uses: actions/checkout@v2
        # Checkout code to the GitHub Actions runner

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          # Set up the node version you are using

      - name: Install Dependencies
        run: npm install
        # Install npm dependencies

      - name: Run Tests
        run: npm test
        env:
          REACT_APP_DEEPSEEK_API: ${{ secrets.DEEPSEEK_API }}
        # Run test script defined in package.json, providing the API key as an environment variable